version: '3.7'
services:
  go-mailjet-api-relay:
    build: .
    ports:
      - "8080:80"
    environment:
      RECAPTCHA_SECRET: ${RECAPTCHA_SECRET}
      MAILJET_PRIVATE_KEY: ${MAILJET_PRIVATE_KEY}
      MAILJET_PUBLIC_KEY: ${MAILJET_PUBLIC_KEY}
      EMAIL: ${EMAIL}
      
